name: CI

on:  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2

            -
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - uses: docker/build-push-action@v3
              with:
                dockerfile: 'Dockerfile'
                tags: mkokoko/react:latest