name: CI

on:  push



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            - run: cat .github/workflows/variables/dev.env >> $GITHUB_ENV
            # - 
            #   name: Set Environment variables
            #   uses: ./.github/actions/setvars
            #   with:
            #     varFilePath: ./.github/variables/myvars.env
            -
              name: Login to ECR
              uses: docker/login-action@v2
              with:
                registry: ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION}}.amazonaws.com
                username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - 
              name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                file: "./.github/workflows/Dockerfile"
                tags: |
                  mkokoko/react:${{ github.sha }}
                  mkokoko/react:dev
                  ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION}}.amazonaws.com/java:${{ github.sha }}
                  ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION}}.amazonaws.com/java:dev
            