name: CI

on:  push



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2

            -
              name: Login to ECR
              uses: docker/login-action@v2
              with:
                registry: 482720962971.dkr.ecr.us-east-1.amazonaws.com
                username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            -
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - 
              name: Build and push
              uses: docker/build-push-action@v3
              with:
                context: .
                push: true
                file: "./.github/workflows/Dockerfile"
                tags: |
                  mkokoko/react:${{ GITHUB_SHA }}
                  482720962971.dkr.ecr.us-east-1.amazonaws.com/java:${{ env.GITHUB_SHA }}
            