name: CI

on:  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
    
            - uses: docker/build-push-action@v1
              with:
                dockerfile: 'Dockerfile'
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: mkokoko/react
                tags: latest